title: Building Digital Exhibits with Omeka
remote_theme: ubc-library-rc/rc-workshop-template
footer_content: "<a href=\"https://github.com/donna-langille/buildingdigitalexhibits/\">View in GitHub</a>"
